### PR TITLE
Removes dates tsv file from Symphony mount.

### LINKED ISSUE #157: dates.tsv files should be moved from the symphony mount after processing
After the auto_bib_loads and symphony_marc_import DAGs run, the *.dates.tsv files are still in the mount on the symphony server.

### PR DESCRIPTION
**Pull request by shelleydoljack**
Closes #157

### CODE REVIEW

**Review by jermnelson — APPROVED** [review]

**Review by jgreben — APPROVED** [review]

**Review by jgreben — CHANGES_REQUESTED** [review]
Maybe just write a test so coveralls is happy..

**Comment by jermnelson** [comment]
Approving but could add the following to test at https://github.com/sul-dlss/libsys-airflow/blob/578a34b6eadc6cc14133e7cfd2468cb34038a84c/plugins/tests/test_instances.py#L50, 
```assert not tsv_dates_file.exists()``` to keep the current coverage.

**Comment by shelleydoljack** [comment]
I thought about writing a test too, but I don't think testing the `.unlink()` function is necessary. I can't stick `assert not tsv_dates_file.exists()` into `test_adjust_records` because `_adjust_records` doesn't do the unlink, it is the `run_bibs_transformer` method that does. I tried looking at re-writing `test_run_bibs_transformer` but it is more involved to do that for testing an python function. 🤷

**Comment by jgreben** [comment]
Can you just move the unlink() to the _adjust_records function then? Otherwise, what do you want to do about the coverage? Usually the inability to test something means something probably needs to be refactored.

**Review by jgreben — APPROVED** [review]

**Pull request merged**
