### PR TITLE
Remove extra template and update README

### PR DESCRIPTION
**Pull request by justinlittman**
Edit by @lwrubel: It seems that the Variables are necessary for importing DAGs and including viewing plugin apps. Locally, these are added via a `.env`.

### CODE REVIEW

**Comment by lwrubel** [comment]
It wouldn't hurt for someone else to test this locally.

**Review by ndushay — CHANGES_REQUESTED** [review]
This PR removes the healthcheck ... was that unintentional?  Is a rebase needed?

**Comment by lwrubel** [comment]
Yes, it is a duplicate, leftover from before the move of the directory. See `libsys-airflow/libsys_airflow/plugins/folio/templates/healthcheck/index.html`

**Review by jmartin-sul — APPROVED** [review]

**Comment by lwrubel** [comment]
@ndushay are there still any concerns? May I merge this?

**Pull request merged**
