### PR TITLE
Add alembic database migrations to deployments

### LINKED ISSUE #372: Investigate adding alembic database migrations to the capistrano deployment
We use capistrano and our `dlss-capistrano` extension for deployment. Investigate adding alembic based database migrations to the `dlss-capistrano` migration so that we avoid needing to manually run migrations on servers and the potential for error or missing migrations on deployment.

### PR DESCRIPTION
**Pull request by mjgiarlo**
Fixes #372

This commit instructs Capistrano to ensure the necessary databases are created and then run database migrations as part of the `deploy:restart` task. To accomplish this, a few parts are added:

* A custom `db:create` task in `config/deploy.rb` that adapts the code in `docker/init-multi-postgres-dbs.sh`
* New DB migration-related tasks:
  * `alembic:migrate`: to apply migrations
  * `alembic:current`: to show the current migration (for troubleshooting)
  * `alembic:history`: to show the migration history (for troubleshooting)
* Add alembic and psycopg2 as Python dependencies (above tasks fail without this)

# Demonstration

I successfully ran `cap stage deploy deploy:restart` and it finished with the following:

```shell
...
01:05 db:create
      01 psql         -v ON_ERROR_STOP=1 postgresql://$DATABASE_USERNAME:$DATABASE_PASSWORD@$DATABASE_HOSTNAME <<-SQL
        SELECT…
      01 GRANT
      01 GRANT
    ✔ 01 libsys@sul-libsys-airflow-stage.stanford.edu 0.153s
01:05 alembic:migrate
      01 cd /home/libsys/libsys-airflow/releases/20230515191421 && source /home/libsys/virtual-env/bin/activate && poetry run alembi…
      01 INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
      01 INFO  [alembic.runtime.migration] Will assume transactional DDL.
      01 INFO  [alembic.runtime.migration] Running upgrade  -> 965229094874, Create vendors table
      01 INFO  [alembic.runtime.migration] Running upgrade 965229094874 -> 55557ab268c9, add vendor_interface model
    ✔ 01 libsys@sul-libsys-airflow-stage.stanford.edu 1.058s
```

After the deployment ran, I tested the DB migration tasks one-by-one to confirm the server was in the state I expected:

```shell
$ cap stage alembic:migrate    
00:00 alembic:migrate
      01 cd /home/libsys/libsys-airflow/current && source /home/libsys/virtual-env/bin/activate && poetry run alembic upgrade head
      01 INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
      01 INFO  [alembic.runtime.migration] Will assume transactional DDL.
    ✔ 01 libsys@sul-libsys-airflow-stage.stanford.edu 1.286s

$ cap stage alembic:current
00:00 alembic:current
      01 cd /home/libsys/libsys-airflow/current && source /home/libsys/virtual-env/bin/activate && poetry run alembic current
      01 INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
      01 INFO  [alembic.runtime.migration] Will assume transactional DDL.
      01 55557ab268c9 (head)
    ✔ 01 libsys@sul-libsys-airflow-stage.stanford.edu 1.274s

$ cap stage alembic:history
00:00 alembic:history
      01 cd /home/libsys/libsys-airflow/current && source /home/libsys/virtual-env/bin/activate && poetry run alembic history --verb…
      01 Rev: 55557ab268c9 (head) 
      01 Parent: 965229094874
      01 Path: /home/libsys/libsys-airflow/releases/20230515191421/vendor_loads_migration/versions/55557ab268c9_add_vendor_interface…
      01
      01     add vendor_interface model
      01
      01     Revision ID: 55557ab268c9
      01     Revises: 965229094874
      01     Create Date: 2023-05-03 10:21:46.652162
      01
      01 Rev: 965229094874
      01 Parent: <base>
      01 Path: /home/libsys/libsys-airflow/releases/20230515191421/vendor_loads_migration/versions/965229094874_create_vendors_table…
      01
      01     Create vendors table 
      01
      01     Revision ID: 965229094874
      01     Revises:
      01     Create Date: 2023-05-01 14:45:09.973516
      01
    ✔ 01 libsys@sul-libsys-airflow-stage.stanford.edu 1.200s
```

# Complication?

Not sure if this is a consequence of this PR, or not, but I am now seeing some errors when the `airflow-init` docker-compose container starts (happens immediately before the new DB-related tasks):

```shell
01 Attaching to 20230515205921-airflow-init-1                                                                                  
      01 20230515205921-airflow-init-1  | /home/airflow/.local/lib/python3.10/site-packages/airflow/configuration.py:454 Deprecation…
      01 20230515205921-airflow-init-1  | /home/airflow/.local/lib/python3.10/site-packages/airflow/configuration.py:380 Deprecation…
      01 20230515205921-airflow-init-1  | /home/airflow/.local/lib/python3.10/site-packages/airflow/settings.py:188 DeprecationWarni…
      01 20230515205921-airflow-init-1  | The container is run as root user. For security, consider using a regular user account.    
      01 20230515205921-airflow-init-1  |                                                                                            
      01 20230515205921-airflow-init-1  | /home/airflow/.local/lib/python3.10/site-packages/airflow/configuration.py:454 Deprecation…
      01 20230515205921-airflow-init-1  | /home/airflow/.local/lib/python3.10/site-packages/airflow/configuration.py:380 Deprecation…
      01 20230515205921-airflow-init-1  | /home/airflow/.local/lib/python3.10/site-packages/airflow/settings.py:188 DeprecationWarni…
      01 20230515205921-airflow-init-1  | /home/airflow/.local/lib/python3.10/site-packages/airflow/models/base.py:70 DeprecationWar…
      01 20230515205921-airflow-init-1  | /home/airflow/.local/lib/python3.10/site-packages/airflow/utils/sqlalchemy.py:47 Deprecati…
      01 20230515205921-airflow-init-1  | DB: postgresql+psycopg2://libsys:***@sul-libsys-airflow-db-stage-a.stanford.edu/libsys     
      01 20230515205921-airflow-init-1  | Performing upgrade with database postgresql+psycopg2://libsys:***@sul-libsys-airflow-db-st…
      01 20230515205921-airflow-init-1  | [2023-05-15T21:00:07.951+0000] {migration.py:207} INFO - Context impl PostgresqlImpl.      
      01 20230515205921-airflow-init-1  | [2023-05-15T21:00:07.954+0000] {migration.py:210} INFO - Will assume transactional DDL.    
      01 20230515205921-airflow-init-1  | [2023-05-15T21:00:07.963+0000] {db.py:1588} INFO - Creating tables                         
      01 20230515205921-airflow-init-1  | INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.                             
      01 20230515205921-airflow-init-1  | INFO  [alembic.runtime.migration] Will assume transactional DDL.                           
      01 20230515205921-airflow-init-1  | /home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py:346 RemovedInAi…
      01 20230515205921-airflow-init-1  | ERROR [airflow.models.dagbag.DagBag] Failed to import: /opt/airflow/libsys_airflow/dags/bi…
      01 20230515205921-airflow-init-1  | Traceback (most recent call last):                                                         
      01 20230515205921-airflow-init-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line …
      01 20230515205921-airflow-init-1  |     loader.exec_module(new_module)                                                         
      01 20230515205921-airflow-init-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module                  
      01 20230515205921-airflow-init-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed             
      01 20230515205921-airflow-init-1  |   File "/opt/airflow/libsys_airflow/dags/bib_records.py", line 66, in <module>             
      01 20230515205921-airflow-init-1  |     sul_config = LibraryConfiguration(                                                     
      01 20230515205921-airflow-init-1  |   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__                   
      01 20230515205921-airflow-init-1  | pydantic.error_wrappers.ValidationError: 1 validation error for LibraryConfiguration       
      01 20230515205921-airflow-init-1  | base_folder                                                                                
      01 20230515205921-airflow-init-1  |   file or directory at path "/opt/airflow/migration" does not exist (type=value_error.path…
      01 20230515205921-airflow-init-1  | WARNI [airflow.task.operators] Dependency <Task(_PythonDecoratedOperator): setup>, filter_…
      01 20230515205921-airflow-init-1  | WARNI [airflow.task.operators] Dependency <Task(_PythonDecoratedOperator): filter_fields_t…
      01 20230515205921-airflow-init-1  | WARNI [airflow.task.operators] Dependency <Task(_PythonDecoratedOperator): setup>, batch_t…
      01 20230515205921-airflow-init-1  | WARNI [airflow.task.operators] Dependency <Task(_PythonDecoratedOperator): batch_task>, se…
      01 20230515205921-airflow-init-1  | WARNI [airflow.task.operators] Dependency <Task(_PythonDecoratedOperator): setup>, data_im…
      01 20230515205921-airflow-init-1  | WARNI [airflow.task.operators] Dependency <Task(_PythonDecoratedOperator): data_import_tas…
      01 20230515205921-airflow-init-1  | WARNI [airflow.task.operators] Dependency <Task(_PythonDecoratedOperator): setup>, ftp_dow…
      01 20230515205921-airflow-init-1  | WARNI [airflow.task.operators] Dependency <Task(_PythonDecoratedOperator): ftp_download_ta…
      01 20230515205921-airflow-init-1  | WARNI [airflow.task.operators] Dependency <Task(_PythonDecoratedOperator): setup>, ftp_dow…
      01 20230515205921-airflow-init-1  | WARNI [airflow.task.operators] Dependency <Task(_PythonDecoratedOperator): ftp_download_ta…
      01 20230515205921-airflow-init-1  | WARNI [airflow.task.operators] Dependency <Task(_PythonDecoratedOperator): setup>, ftp_dow…
      01 20230515205921-airflow-init-1  | WARNI [airflow.task.operators] Dependency <Task(_PythonDecoratedOperator): ftp_download_ta…
      01 20230515205921-airflow-init-1  | WARNI [airflow.task.operators] Dependency <Task(_PythonDecoratedOperator): setup>, ftp_dow…
      01 20230515205921-airflow-init-1  | WARNI [airflow.task.operators] Dependency <Task(_PythonDecoratedOperator): ftp_download_ta…
      01 20230515205921-airflow-init-1  | WARNI [airflow.task.operators] Dependency <Task(_PythonDecoratedOperator): setup>, archive…
      01 20230515205921-airflow-init-1  | WARNI [airflow.task.operators] Dependency <Task(_PythonDecoratedOperator): archive_task>, …
      01 20230515205921-airflow-init-1  | WARNI [airflow.decorators.base.DecoratedMappedOperator] Dependency <Task(_PythonDecoratedO…
      01 20230515205921-airflow-init-1  | WARNI [airflow.decorators.base.DecoratedMappedOperator] Dependency <Mapped(_PythonDecorate…
      01 20230515205921-airflow-init-1  | WARNI [airflow.decorators.base.DecoratedMappedOperator] Dependency <Task(_PythonDecoratedO…
      01 20230515205921-airflow-init-1  | WARNI [airflow.decorators.base.DecoratedMappedOperator] Dependency <Mapped(_PythonDecorate…
      01 20230515205921-airflow-init-1  | WARNI [airflow.decorators.base.DecoratedMappedOperator] Dependency <Task(_PythonDecoratedO…
      01 20230515205921-airflow-init-1  | WARNI [airflow.decorators.base.DecoratedMappedOperator] Dependency <Mapped(_PythonDecorate…
      01 20230515205921-airflow-init-1  | WARNI [airflow.decorators.base.DecoratedMappedOperator] Dependency <Task(_PythonDecoratedO…
      01 20230515205921-airflow-init-1  | WARNI [airflow.decorators.base.DecoratedMappedOperator] Dependency <Mapped(_PythonDecorate…
      01 20230515205921-airflow-init-1  | Upgrades done
```

Happy to take advice on whether to handle that here, elsewhere, or ignore it.

### CODE REVIEW

**Comment by ndushay** [comment]
The errors above are familiar to me.  Perhaps they should be ticketed -- they have to do with libsys fixture data, I believe, and can be safely ignored by us.

Not sure they should continue to be ignored forever, tho.

**Comment by mjgiarlo** [comment]
@jermnelson @aaron-collier Given what @ndushay says above, could y'all comment on this output from the `airflow-init` docker-compose service when it runs as part of starting airflow?

```
      01 20230515205921-airflow-init-1  | ERROR [airflow.models.dagbag.DagBag] Failed to import: /opt/airflow/libsys_airflow/dags/bi…
      01 20230515205921-airflow-init-1  | Traceback (most recent call last):                                                         
      01 20230515205921-airflow-init-1  |   File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line …
      01 20230515205921-airflow-init-1  |     loader.exec_module(new_module)                                                         
      01 20230515205921-airflow-init-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module                  
      01 20230515205921-airflow-init-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed             
      01 20230515205921-airflow-init-1  |   File "/opt/airflow/libsys_airflow/dags/bib_records.py", line 66, in <module>             
      01 20230515205921-airflow-init-1  |     sul_config = LibraryConfiguration(                                                     
      01 20230515205921-airflow-init-1  |   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__                   
      01 20230515205921-airflow-init-1  | pydantic.error_wrappers.ValidationError: 1 validation error for LibraryConfiguration       
      01 20230515205921-airflow-init-1  | base_folder                                                                                
      01 20230515205921-airflow-init-1  |   file or directory at path "/opt/airflow/migration" does not exist (type=value_error.path…
```

Is this a problem worth ticketing? Part of this alembic work or orthogonal? I'm trying to determine if the alembic stuff is worth undrafting.

**Comment by jermnelson** [comment]
> Is this a problem worth ticketing? Part of this alembic work or orthogonal? I'm trying to determine if the alembic stuff is worth undrafting.

The specific error ` pydantic.error_wrappers.ValidationError` is being generated by the `folio_migration_tools` LibraryConfiguration in the `bib_records` DAG. I'm not sure why the DAG is being imported during the **airflow-init** maybe as part of the Airflow migration process. If the `bib_records` DAG functions properly after Airflow is up I think we can ignore this error message for now.

**Comment by mjgiarlo** [comment]
@jermnelson I don't see that DAG in stage. Might the error above be the cause of it not appearing? https://sul-libsys-airflow-stage.stanford.edu/home?status=all

**Comment by jermnelson** [comment]
> @jermnelson I don't see that DAG in stage. Might the error above be the cause of it not appearing? https://sul-libsys-airflow-stage.stanford.edu/home?status=all

Sorry, the `bib_records` is the name of the module, the DAG it contains is `symphony_marc_import` which is present on folio-stage.

**Comment by mjgiarlo** [comment]
@jermnelson tested and the symphony_marc_import` DAG is still working in stage, so we think this PR does not break the Airflow init process.

**Review by aaron-collier — APPROVED** [review]

**Pull request merged**
