### PR TITLE
Fix expected data structure for adding marc 979 tags

### LINKED ISSUE #1306: Bookplates add_979_marc_tags Task Error
Seeing this stack-trace in each DAG run of `digital_bookplate_979` task `add_979_marc_tags`:
```
*** Found local files:
***   * /opt/airflow/logs/dag_id=digital_bookplate_979/run_id=manual__2024-10-18T22:49:17.865267+00:00/task_id=add_979_marc_tags/attempt=2.log
[2024-10-18, 22:50:27 UTC] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: digital_bookplate_979.add_979_marc_tags manual__2024-10-18T22:49:17.865267+00:00 [queued]>
[2024-10-18, 22:50:27 UTC] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: digital_bookplate_979.add_979_marc_tags manual__2024-10-18T22:49:17.865267+00:00 [queued]>
[2024-10-18, 22:50:27 UTC] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-10-18, 22:50:27 UTC] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): add_979_marc_tags> on 2024-10-18 22:49:17.865267+00:00
[2024-10-18, 22:50:27 UTC] {standard_task_runner.py:60} INFO - Started process 99393 to run task
[2024-10-18, 22:50:27 UTC] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'digital_bookplate_979', 'add_979_marc_tags', 'manual__2024-10-18T22:49:17.865267+00:00', '--job-id', '50996', '--raw', '--subdir', 'DAGS_FOLDER/digital_bookplates/digital_bookplate_979.py', '--cfg-path', '/tmp/tmpd1wqqrjm']
[2024-10-18, 22:50:27 UTC] {standard_task_runner.py:88} INFO - Job 50996: Subtask add_979_marc_tags
[2024-10-18, 22:50:27 UTC] {task_command.py:423} INFO - Running <TaskInstance: digital_bookplate_979.add_979_marc_tags manual__2024-10-18T22:49:17.865267+00:00 [running]> on host 577e21c64556
[2024-10-18, 22:50:27 UTC] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='libsys' AIRFLOW_CTX_DAG_ID='digital_bookplate_979' AIRFLOW_CTX_TASK_ID='add_979_marc_tags' AIRFLOW_CTX_EXECUTION_DATE='2024-10-18T22:49:17.865267+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-18T22:49:17.865267+00:00'
[2024-10-18, 22:50:27 UTC] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/libsys_airflow/plugins/digital_bookplates/bookplates.py", line 146, in add_979_marc_tags
    fund_name = tag_data.get('fund_name', None)
                ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
```

### PR DESCRIPTION
**Pull request by jgreben**
Fixes #1306

### CODE REVIEW

**Review by shelleydoljack — CHANGES_REQUESTED** [review]
I'm not sure this will work. Is there another way to handle this error dowstream? Let me check with Acquisitions staff is this is likely: an invoice line has multiple fund distributions that are bookplate funds, the invoice lines is linked to 1 po line, which is linked to 1 instance ID. So add 979's coming from that side of the workflow (acqusitions), would send a list of bookplates data with one instance ID.

**Comment by jgreben** [comment]
> I'm not sure this will work. Is there another way to handle this error dowstream? Let me check with Acquisitions staff is this is likely: an invoice line has multiple fund distributions that are bookplate funds, the invoice line is linked to 1 po line, which is linked to 1 instance ID. So add 979's coming from that side of the workflow (acqusitions), would send a list of bookplates data with one instance ID.

I'm not sure there is a way to handle the error differently. The data structure changed from what was initially expected since the 10/18 run. What will the expected return_value of the launch_add_979_fields_task alway be? It's not clear to me when trying to trace it back in the code. @jermnelson and I were working at this from different angles and maybe there is a disconnect?

**Comment by shelleydoljack** [comment]
According to Suzette, it is very likely for an invoice line to have been paid on multiple bookplate funds, which would link up to 1 instance ID. Here are two examples:
invoice line ID `a807554d-1e77-4f5a-8c15-b47581e7083c` has the following fund distribution and po line data:
```
<snip>
fundDistributions":[
  {
    "code": "STANDISH-SUL",
    "encumbrance": "765656b7-0376-431e-83ef-c71246f9804c",
    "fundId": "eb03e7c7-e712-4fdb-b1ee-7dcf325808de",
    "distributionType": "percentage",
    "value": 33.0
  },
  {
    "code": "MUFFLEY-SUL",
    "encumbrance": "a88fcd49-41c1-49f9-a037-7733e5d666dd",
    "fundId": "a47e79ab-6f93-4e6e-86b3-1dff3fb0dde7",
    "distributionType": "percentage",
    "value": 34.0
  },
  {
    "code": "JAGELS-SUL",
    "encumbrance": "ec2c512c-5e62-4c97-ae72-6f1c94322ae5",
    "fundId": "325437c2-b88e-4708-8681-a57870efc221",
    "distributionType": "percentage",
    "value": 33.0
  }
],
"invoiceId": "c40267e2-2ef7-4409-b680-e98794a17886",
"invoiceLineNumber": "1",
"invoiceLineStatus": "Paid",
"poLineId": "ad1f9b12-8371-4fd9-8c9d-a8f7c6e13f4b",
<snip>
```
All those funds are digital bookplate funds. The po line is linked to instance ID `"instanceId": "973c5ecc-dac1-41b0-8ced-f44fb1b32cda",`.

Here is the second example Suzette provided, invoice line `39ba5b63-de98-4843-88ca-cc0f4adfcd23`:
```
"fundDistributions": [
      {
          "code": "STEINMETZ-SUL",
          "encumbrance": "2e0765a0-b137-4d58-9e88-cc7394e1e5d7",
          "fundId": "fced6c53-61fb-48c6-821f-14cff3c39b59",
          "distributionType": "percentage",
          "value": 50.0
      },
      {
          "code": "WHITEHEAD-SUL",
          "encumbrance": "df477c4c-a324-4ffd-a999-8aff94743b29",
          "fundId": "694c5236-ada2-4d5f-8e12-ad61ddb4a426",
          "distributionType": "percentage",
          "value": 50.0
      }
  ],
  "invoiceId": "cf11f295-2363-4754-bccf-a614b9fc46c0",
  "invoiceLineNumber": "1",
  "invoiceLineStatus": "Paid",
  "poLineId": "ccee2e77-6c14-40b6-9e77-192b54576e34",
```
The po line is linked to instance ID `b6e80385-3be3-4e84-a530-d89d072af46b`. When the invoice lines are checked to see if the fund distributions contain a bookplate fund, it should be appending bookplate data to the list. Now I'm not sure if [it will correctly append all bookplate data and repeat the po line ID](https://github.com/sul-dlss/libsys-airflow/blob/8de157570b47e606fe91fe64b978be41e9927668/libsys_airflow/plugins/digital_bookplates/bookplates.py#L87-L96) for these 2 examples. There is a [mock fixture for invoice lines that is similar](https://github.com/sul-dlss/libsys-airflow/blob/8de157570b47e606fe91fe64b978be41e9927668/tests/digital_bookplates/test_bookplates_funds.py#L76-L103) (2 of the funds are bookplate funds) so maybe it is working correctly in that the [list contains 2 objects with the same po line ID and different bookplates](https://github.com/sul-dlss/libsys-airflow/blob/8de157570b47e606fe91fe64b978be41e9927668/tests/digital_bookplates/test_bookplates_funds.py#L145-L162). So then maybe those won't be an issue since each item in the list for bookplate_polines_funds will go to [instances_from_po_lines](https://github.com/sul-dlss/libsys-airflow/blob/8de157570b47e606fe91fe64b978be41e9927668/libsys_airflow/plugins/digital_bookplates/bookplates.py#L166) and return one instance with one bookplate data.

**Review by shelleydoljack — APPROVED** [review]
I'm changing this to Approved after working through it more on the [comment here](https://github.com/sul-dlss/libsys-airflow/pull/1316#issuecomment-2430341783).

**Comment by jgreben** [comment]
I'm not sure what to do with all that info. I thought that now with the 979 polling dag it would always send one bookplate druid per instance uuid, and that is what I see as the return value for all the failed dag runs, and that is what this PR addresses. Maybe we need a story time for this.

**Comment by jgreben** [comment]
The current data structure is fine, only the return from the UI needs to change.

**Pull request closed without merging**
